version: "3.8"

services:

  postgres:
    build: ./postgres
    environment:
      - POSTGRES_PASSWORD=evolve-credit
      - POSTGRES_USER=postgres
      - POSTGRES_DB=evolve-credit
    ports:
      - 5432:5432
    volumes: 
      - ./postgres/data:/app/postgres/data

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - DB_SOURCE=postgresql://postgres:evolve-credit@postgres:5432/evolve-credit?sslmode=disable
    depends_on:
      - postgres
    command: ["./main"]
    entrypoint: ["./wait-for.sh", "postgres:5432", "--"]

volumes:
  data:
